<?php
// femmes
$femmes = [
    [
    'lastname' => 'DOE',
    'firstname' => 'Jane',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '1.jpg',
    'description' => 'Je suis une femme qui ...',
    'is_enabled' => true,
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'Test1',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '3.jpg',
    'description' => 'Je suis une femme qui ...',
    'is_enabled' => true,
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'Test2',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '7.jpg',
    'description' => 'Je suis une femme qui ...',
    'is_enabled' => true,
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'Test3',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '20.jpg',
    'description' => 'Je suis une femme qui ...',
    'is_enabled' => true,
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'Test4',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '21.jpg',
    'description' => 'Je suis une femme qui ...',
    'is_enabled' => true,
    ],
];

$hommes = [
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => 'image.jpg',
    'description' => 'Je suis une homme qui ...',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => 'image.jpg',
    'description' => 'Je suis une homme qui ...',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => 'image.jpg',
    'description' => 'Je suis une homme qui ...',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => 'image.jpg',
    'description' => 'Je suis une homme qui ...',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => 'image.jpg',
    'description' => 'Je suis une homme qui ...',
    ],
];

?>