<?php

// femmes
$femmes = [
    [
    'lastname' => 'Charbonneau',
    'firstname' => 'Zurie',
    'age' => '25',
    'gender' => 'femme',
    'mail' => 'zurieCharbonneau@dayrep.com',
    'zipcode' => '94200',
    'picture' => '1.jpg',
    'description' => 'Nullam vitae ex porta, molestie ligula dictum, elementum massa. Nulla vitae quam est. Mauris bibendum odio et ex hendrerit varius.',
    ],
    [
    'lastname' => 'Chaloux',
    'firstname' => 'Pansy',
    'age' => '35',
    'gender' => 'femme',
    'mail' => 'pansychalouxe@mail.com',
    'zipcode' => '83300',
    'picture' => '96.jpg',
    'description' => 'Etiam accumsan ornare nibh, at sollicitudin velit feugiat non. In gravida fermentum dui. Nunc porttitor quam ac elit blandit, ut iaculis tellus venenatis.',
    ],
    [
    'lastname' => 'Petrie',
    'firstname' => 'Alita',
    'age' => '23',
    'gender' => 'femme',
    'mail' => 'petriealita@yahoo.fr',
    'zipcode' => '13015',
    'picture' => '7.jpg',
    'description' => 'Nullam fringilla, nibh non pulvinar accumsan, felis ante maximus ligula, viverra feugiat lorem lacus venenatis augue. Senectus et netus et malesuada fames.',
    ],
    [
    'lastname' => 'Morin',
    'firstname' => 'Marie',
    'age' => '42',
    'gender' => 'femme',
    'mail' => 'mariemorin@mail.fr',
    'zipcode' => '80000',
    'picture' => '20.jpg',
    'description' => 'Fusce purus massa, accumsan id orci ut, accumsan ullamcorper turpis. Aenean metus risus, consequat vitae volutpat at, pharetra at mauris.',
    ],
    [
    'lastname' => 'Jupiler',
    'firstname' => 'Coralie',
    'age' => '33',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '21.jpg',
    'description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut voluptas sequi nesciunt vitae nemo quam eligendi.',
    ],
    [
    'lastname' => 'Goudal',
    'firstname' => 'Manon',
    'age' => '30',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '27.jpg',
    'description' => 'Felis ante maximus ligula, viverra feugiat lorem lacus venenatis augue. Pellentesque habitant morbi tristique senectus.',
    ],
    [
    'lastname' => 'Orval',
    'firstname' => 'Emilie',
    'age' => '35',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '16.jpg',
    'description' => 'Integer sit amet facilisis justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    ],
    [
    'lastname' => 'Labrosse',
    'firstname' => 'Maurane',
    'age' => '28',
    'gender' => 'femme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '100.jpg',
    'description' => 'Non pulvinar accumsan, felis ante maximus ligula, viverra feugiat lorem lacus venenatis augue. Lacus eu ante scelerisque ornare.',
    ],
];

$hommes = [
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '14.jpg',
    'description' => 'Integer sit amet facilisis justo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '29.jpg',
    'description' => 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut voluptas sequi nesciunt vitae nemo illo reiciendis quam eligendi.',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '34.jpg',
    'description' => 'Aut voluptas sequi nesciunt vitae nemo illo reiciendis porro ex maxime eius saepe laborum, perspiciatis ipsa possimus quam eligendi.',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '45.jpg',
    'description' => 'Nullam fringilla, nibh non pulvinar accumsan, felis ante maximus ligula, viverra feugiat lorem lacus venenatis augue.',
    ],
    [
    'lastname' => 'DOE',
    'firstname' => 'John',
    'age' => '33',
    'gender' => 'homme',
    'mail' => 'john.doe@exemple.com',
    'zipcode' => '76000',
    'picture' => '46.jpg',
    'description' => 'Viverra feugiat lorem lacus venenatis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.',
    ],
];
